#!/usr/bin/env bash
set -Eeuo pipefail

# Intended for tmux status-right via:
#   set -g status-interval 5
#   set -g status-right '#(~/.local/lib/agent-workflow/tmux-status-line.sh)'
#
# Production implementation should read one atomically written, bounded cache
# generated by `agent-workflow tmux snapshot`; it should not scan run directories
# or invoke many tmux commands on every repaint.

cache="${XDG_CACHE_HOME:-$HOME/.cache}/agent-workflow/operator-summary.tsv"

green=0 yellow=0 red=0 neutral=0
if [[ -r "$cache" ]]; then
  while IFS=$'\t' read -r light count; do
    case "$light" in
      green) green="$count" ;;
      yellow) yellow="$count" ;;
      red) red="$count" ;;
      neutral) neutral="$count" ;;
    esac
  done < "$cache"
fi

# tmux 256-color values: green=34, amber=214, red=196, neutral=245.
printf '#[fg=colour34,bold]●%s #[fg=colour214,bold]◆%s #[fg=colour196,bold]◆%s #[fg=colour245]○%s#[default]' \
  "$green" "$yellow" "$red" "$neutral"
